### ISSUE TITLE
There were some errors deploying the backend

### ISSUE THREAD

**Issue by VMCoud** [QianheYu/headscale-panel#2]
2023-08-31 06:36:15	INFO	routes/routes.go:63	headscale-panel/routes.InitRoutes	Initialization route is completed！
2023-08-31 06:36:15	INFO	src/main.go:75	main.main	Server is running at 0.0.0.0:8088/api
2023-08-31 06:36:15	DEBUG	tasks/headscale.go:30	headscale-panel/tasks.(*HeadscaleService).Start	create process
2023-08-31 06:36:15	DEBUG	tasks/headscale.go:34	headscale-panel/tasks.(*HeadscaleService).Start	start inside control process
2023-08-31 06:36:15	INFO	tasks/headscale.go:53	headscale-panel/tasks.(*HeadscaleService).Start	Download and install the headscale
2023-08-31 06:36:16	ERROR	src/main.go:79	main.main	json: cannot unmarshal object into Go value of type []*task.Release
panic: json: cannot unmarshal object into Go value of type []*task.Release

goroutine 1 [running]:
main.main()
	/src/main.go:80 +0x58e

**Comment by VMCoud** [comment]
Calls to the headscale related api all report a request failure error, status code 500.

**Comment by VMCoud** [comment]
You can log in to the control panel, but you can't ui manage it.

**Comment by VMCoud** [comment]
2023-08-31 06:28:40	WARN	tasks/headscale.go:162	headscale-panel/tasks.(*HeadscaleService).checkProcess	headscale process is not running, restart it
2023-08-31 06:28:40	ERROR	tasks/headscale.go:165	headscale-panel/tasks.(*HeadscaleService).checkProcess	deamon stop headscale process error: exit status 1
inside process started
[GIN] 2023/08/31 - 06:28:

**Comment by VMCoud** [comment]
[GIN-debug] DELETE /api/console/route        --> headscale-panel/controller.RouteController.DeleteRoute-fm (8 handlers)
[GIN-debug] GET    /api/console/machine      --> headscale-panel/controller.IMachinesController.GetMachines-fm (8 handlers)
[GIN-debug] POST   /api/console/machine      --> headscale-panel/controller.IMachinesController.StateMachines-fm (8 handlers)
[GIN-debug] DELETE /api/console/machine      --> headscale-panel/controller.IMachinesController.DeleteMachine-fm (8 handlers)
[GIN-debug] PUT    /api/console/machine      --> headscale-panel/controller.IMachinesController.MoveMachine-fm (8 handlers)
[GIN-debug] PATCH  /api/console/machine      --> headscale-panel/controller.IMachinesController.SetTags-fm (8 handlers)
[GIN-debug] GET    /api/console/acl          --> headscale-panel/controller.AccessControlController.GetAccessControl-fm (8 handlers)
[GIN-debug] POST   /api/console/acl          --> headscale-panel/controller.AccessControlController.SetAccessControl-fm (8 handlers)
2023-08-31 09:32:27	INFO	routes/routes.go:63	headscale-panel/routes.InitRoutes	Initialization route is completed！
2023-08-31 09:32:27	INFO	src/main.go:75	main.main	Server is running at 0.0.0.0:8088/api
2023-08-31 09:32:27	DEBUG	tasks/headscale.go:30	headscale-panel/tasks.(*HeadscaleService).Start	create process
2023-08-31 09:32:27	DEBUG	tasks/headscale.go:34	headscale-panel/tasks.(*HeadscaleService).Start	start inside control process
2023-08-31 09:32:27	INFO	tasks/headscale.go:85	headscale-panel/tasks.(*HeadscaleService).Start	start headscale
inside process started
[GIN] 2023/08/31 - 09:32:28 | 200 |    3.505726ms |  123.128.40.210 | GET      "/api/system/status"
[GIN] 2023/08/31 - 09:32:30 | 200 |     576.706µs |  123.128.40.210 | GET      "/api/system/status"
[GIN] 2023/08/31 - 09:32:32 | 200 |    3.512024ms |  123.128.40.210 | GET      "/api/system/status"
[GIN] 2023/08/31 - 09:32:34 | 200 |     764.529µs |  123.128.40.210 | GET      "/api/system/status"
[GIN] 2023/08/31 - 09:32:36 | 200 |     650.466µs |  123.128.40.210 | GET      "/api/system/status"
2023-08-31 09:32:37	ERROR	tasks/headscale.go:193	headscale-panel/tasks.(*HeadscaleService).checkNewVersion	get latest version error: Get "https://api.github.com/repos/juanfont/headscale/releases": net/http: TLS handshake timeout
[GIN] 2023/08/31 - 09:32:37 | 200 |     684.186µs |  123.128.40.210 | GET      "/api/system/status"
[GIN] 2023/08/31 - 09:32:40 | 200 |     694.069µs |  123.128.40.210 | GET      "/api/system/status"
2023-08-31 09:32:41	ERROR	tasks/headscale_grpc.go:225	headscale-panel/tasks.(*headscaleRPC).unaryClientInterceptor.func1	grpc: /headscale.v1.HeadscaleService/ListApiKeys, duration: 7ms, remote_server: 127.0.0.1:50443, err: rpc error: code = Internal desc = failed to validate token
2023-08-31 09:32:41	INFO	tasks/headscale_grpc.go:191	headscale-panel/tasks.(*headscaleRPC).newApiKey	create API KEY
refresh api key
create a new api key
[GIN] 2023/08/31 - 09:32:41 | 500 |    1.198666ms |  123.128.40.210 | GET      "/api/console/machine"

**Comment by VMCoud** [comment]
![image](https://github.com/QianheYu/headscale-panel/assets/59264435/815be713-67e2-4e4c-97e3-116eaf87d344)

**Comment by VMCoud** [comment]
这个已经找到不能用的原因了，国内VPS不能访问github 无法下载headscale核心
